name: Deploy to GCP

on:
  push:
    # TEST
    # a test line
    branches:
      - deploy

jobs:
  deploy:
    name: Build & Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Get project version from pom.xml
        id: get_version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Submit build to Cloud Build
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/github-ai-bot:$VERSION

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy github-ai-bot \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/github-ai-bot:$VERSION \
            --platform managed \
            --region europe-west1 \
            --allow-unauthenticated
